### PR TITLE
Remove reference to javafx:compile

### PR DESCRIPTION
**Pull request by Gerardwx**
There doesn't appear to be a _compile_ goal in current implementation.

### CODE REVIEW

**Comment by betanzos** [comment]
I agree. This goal was delete in v0.0.4 with this commit [e5de9bc](https://github.com/openjfx/javafx-maven-plugin/commit/e5de9bc653cb1e04724275909eacef6255bb354f).

**Comment by betanzos** [comment]
I think it would even look better like this:

>To compile the project use the maven-compiler-plugin:
>>mvn compile

**Comment by jperedadnr** [comment]
Hi @Gerardwx, as per our [contribution guidelines](https://github.com/openjfx/javafx-maven-plugin#issues-and-contributions), can you sign the CLA before we can proceed?

**Comment by jperedadnr** [comment]
Hey @Gerardwx, about your commits today, are you aware that these are part of your open PR?

**Comment by Gerardwx** [comment]
Sorry, I have to abandon this. I don't have time to deal with the CLA.

**Pull request closed without merging**
